apiVersion: v1
kind: Service
metadata:
  name: myschool-service
spec:
  selector:
    app: myschool
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
      nodePort: 30080
      
